# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: general-log
  queue.type: persisted
  path.config: pipeline/general-log.conf

- pipeline.id: chat-history
  queue.type: persisted
  path.config: pipeline/chat-history.conf
